services:
  db:
    image: postgres:18
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: db
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'PGPASSWORD=${DB_PASSWORD} pg_isready -U user -d db'"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
  backend:
    build: "."
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_PASSWORD=${DB_PASSWORD}
      - PORT=3000
    networks:
      - backend-network
    healthcheck:
      interval: 1m
      timeout: 10s
      retries: 3
      test: ["CMD-SHELL", "curl -f http://localhost:${PORT}/health || exit 1"]

networks:
  backend-network:
    driver: bridge

volumes:
  db_data:
